spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
