CREATE TABLE IF NOT EXISTS product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    image text,
    price bigint NOT NULL,
    description text,
    created_at timestamptz NOT NULL
);