CREATE TABLE IF NOT EXISTS "order" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS product_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint REFERENCES product(id),
    order_id bigint REFERENCES "order"(id),
    price bigint NOT NULL,
    quantity int NOT NULL
);